_BASE_: maskformer2_vit-b_dinov2_bs1_90kequiv.yaml
SOLVER:
  IMS_PER_BATCH: 8
  # Cityscapes has 2975 images in training set, 500 in val
  MAX_ITER: 1440000 # Formula: (# images * # epochs / batch size)
  CHECKPOINT_PERIOD: 18594 # Every 50 epochs
TEST:
  EVAL_PERIOD: 18594 # Every 50 epoch