_BASE_: maskformer2_dinov2_frozen_50ep.yaml
SOLVER:
  IMS_PER_BATCH: 4
  STEPS: (1330729, 1404659) #90%,95% learning rate decay
  MAX_ITER: 1478588 # 50 epochs (118287 * 50 / 4)
  CHECKPOINT_PERIOD: 59144 # every 2 epochs
TEST:
  EVAL_PERIOD: 59144 # every 2 epochs
