_BASE_: ../../timm/maskformer2_vit-b_dinov2_bs1_300ep.yaml
MODEL:
  META_ARCHITECTURE: "MaskFormerUncertainty"
  WEIGHTS: "weightfolder://model_final_VIPER_vit-b_dinov2_300ep.pth"
  SEM_SEG_HEAD:
    NAME: "MaskFormerHeadUncertainty"
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "MultiScaleMaskedTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DROPOUT: 0.0
SEED: -1
TEST:
  EVALUATORS: ("PanopticQualityV3", "saveResults", "SemSegEvaluatorV2")
OUTPUT_DIR: uncert_eval/maskformer2_VIPER_dinov2-vitb_base
