_BASE_: maskformer2_dinov2-vitb_base.yaml
MODEL:
  MASK_FORMER:
    DROPOUT: 0.0
    UNCERTAINTY:
      SEMANTIC_AGGREGATION_METHOD: 'mask_dist'
      INSTANCE_AGGREGATION_METHOD: 'mask_dist'
      PANOPTIC_AGGREGATION_METHOD: 'mask_dist'
      MC_DROPOUT_ENABLED: False
      MC_DROPOUT_SAMPLES: 1
      AGGREGATION_OVERLAP_THRESHOLD: 0.2
      AGGREGATION_VOTE_THRESHOLD: 0.8
      TTA_ENABLED: True
      TTA_TRANSFORMS: ("scale",)
      TIMESERIES_NUM_PREV_FRAMES: 1
INPUT:
  TEST_DATASET_MAPPER_NAME: "timeseries_panoptic"
DATASETS:
  TEST: ("cityscapes_VIPER_format_val_panoptic_with_semseg_time",)
OUTPUT_DIR: uncert_eval/maskformer2_cityscapes_VIPERformat_dinov2-vitb_Time1_TTAscale_mask_dist