_BASE_: maskformer2_ood_R50_base.yaml
MODEL:
  MASK_FORMER:
    DROPOUT: 0.1
    UNCERTAINTY:
      SEMANTIC_AGGREGATION_METHOD: 'mask_dist'
      INSTANCE_AGGREGATION_METHOD: 'mask_dist'
      PANOPTIC_AGGREGATION_METHOD: 'mask_dist'
      MC_DROPOUT_ENABLED: True
      MC_DROPOUT_SAMPLES: 3
      AGGREGATION_OVERLAP_THRESHOLD: 0.2
      AGGREGATION_VOTE_THRESHOLD: 0.8
      TTA_ENABLED: False
      TTA_TRANSFORMS: ("horizontalFlip",)
      TIMESERIES_NUM_PREV_FRAMES: 0
OUTPUT_DIR: uncert_eval/maskformer2_cityscapesOOD_VIPERformat_R50_MC3_mask_dist