_BASE_: maskformer2_vit-s_dinov2_bs1_300ep_thawqkvandproj.yaml
SOLVER:
  IMS_PER_BATCH: 10 # For narval A100
  # VIPER has 13367 images in training set, 4959 in val
  MAX_ITER: 401010 # 300 epochs (# images * # epochs / batch size)
  CHECKPOINT_PERIOD: 13367 # Every 10 epochs
TEST:
  EVAL_PERIOD: 13367 # Every 10 epoch