_BASE_: maskformer2_vit-b_dinov2_bs1_600ep.yaml
SOLVER:
  IMS_PER_BATCH: 6
  # VIPER has 13367 images in training set, 4959 in val
  MAX_ITER: 1336700 # 600 epochs (# images * # epochs / batch size)
  CHECKPOINT_PERIOD: 22278 # Every 10 epochs
OUTPUT_DIR: vit_b_dinov2_VIPER_600ep
TEST:
  EVAL_PERIOD: 22278 # Every 10 epoch